export enum ACTIONS {
  GET_PRODUCT_DATA = 'GET_PRODUCT_DATA',
  SET_PRODUCT_DATA = 'SET_PRODUCT_DATA',

  SET_CART_ITEMS = 'SET_CART_ITEMS',
  INCREMENT_ITEM_COUNT = 'INCREMENT_ITEM_COUNT',
  DECREMENT_ITEM_COUNT = 'DECREMENT_ITEM_COUNT',
}
